import { defineStore } from 'pinia'
export const useCodeStore = defineStore('code', {
  state: () => ({
    codeToNameMap: {
      ABL001: 'English',
      ABL002: 'Japanese',
      ABL003: 'Chinese (Mandarin)',
      ABL004: 'Spanish',
      ABL005: 'French',
      ABL006: 'German',
      ABL007: 'Russian',
      ABL008: 'Italian',
      ABL009: 'Portuguese',
      ABL010: 'Arabic',
      ABL011: 'Hindi',
      ABT001: 'Data Analysis',
      ABT002: 'Machine Learning',
      ABT003: 'Deep Learning',
      ABT004: 'DevOps',
      ABT005: 'Cloud Computing (AWS)',
      ABT006: 'Cloud Computing (Azure)',
      ABT007: 'Cloud Computing (Google Cloud)',
      ABT008: 'Cybersecurity',
      ABT009: 'Network Administration',
      ABT010: 'Database Management (MySQL)',
      ABT011: 'Database Management (PostgreSQL)',
      ABT012: 'Database Management (MongoDB)',
      ABT013: 'Project Management',
      ABT014: 'Agile Methodologies',
      ABT015: 'UI/UX Design',
      ABT016: 'Software Testing',
      ABT017: 'Technical Writing',
      ABT018: 'Business Analysis',
      ABP001: 'Python',
      ABP002: 'Java',
      ABP003: 'C',
      ABP004: 'C++',
      ABP005: 'C#',
      ABP006: 'JavaScript',
      ABP007: 'TypeScript',
      ABP008: 'Ruby',
      ABP009: 'PHP',
      ABP010: 'Swift',
      ABP011: 'Kotlin',
      ABP012: 'R',
      ABP013: 'Go',
      ABP014: 'Rust',
      ABP015: 'Scala',
      ABP016: 'Perl',
      ABP017: 'Haskell',
      ABP018: 'Objective-C',
      ABP019: 'MATLAB',
      ABP020: 'SQL',
      PS001: '팀장',
      PS002: '부서장',
      PS003: '임원',
      PS000: '직책없음',
      RK001: '사원',
      RK002: '대리',
      RK003: '과장',
      RK004: '차장',
      RK005: '부장',
      RK006: '이사',
      RK007: '사장',
      DP001: 'IT사업부',
      DP002: 'IOT사업부',
      DP003: '경영기획부',
      DP004: '인사총무지원부',
      TM001: 'IT영업팀',
      TM002: '해외영업팀',
      TM003: 'IT개발팀',
      TM004: '개발지원팀',
      TM005: 'IOT영업팀',
      TM006: 'IOTPass영업팀',
      TM007: 'IOT개발팀',
      TM008: '경영관리팀',
      TM009: '외주관리팀',
      TM010: '인사지원팀',
      TM011: '총무팀',
      OJS01: '잠실오피스',
      OMP02: '마포오피스',
      OSB03: '성북오피스',
    },
  }),
  actions: {
    getCodeName(code) {
      return this.codeToNameMap[code] || 'Unknown Code'
    },
    getAllAbilities() {
      return Object.keys(this.codeToNameMap).filter(code => code.startsWith('AB'))
    },
  },
})
